# Example property
example.property=I AM TEST

# DataSource settings
spring.datasource.url=jdbc:postgresql://database:5432/ostock_test
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Explicit profile activation
spring.profiles.active=test